# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=60)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('street_address', models.CharField(default='', max_length=120)),
                ('city_address', models.CharField(default='', max_length=60)),
                ('country', models.CharField(default='', max_length=40)),
                ('cell_phone', models.CharField(default='', max_length=18)),
                ('phone', models.CharField(default='', max_length=18)),
                ('pic_height', models.PositiveIntegerField(default=150)),
                ('pic_width', models.PositiveIntegerField(default=150)),
                ('pic_profile', models.ImageField(default='', height_field='pic_height', upload_to='media/images/profile_img', width_field='pic_width')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
