# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='street_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city_address',
            new_name='city',
        ),
    ]
